### ISSUE TITLE
getting cuda runtime error (59) : device-side assert triggered when running imagenet_training.py

### ISSUE THREAD

**Issue by Coderx7** [D-X-Y/ResNeXt-DenseNet#14]
Hi, 
The training procedure using the `main.py` (training CIFAR10/100 etc) runs very well , however, when I tried to use the `imagenet_training.py` I face an error regarding cuda device! 
I execute the `imagenet_training.py` using a simple bash script which is : 
```
MODEL_NAME=resnet18
IMAGENET_DIR=/media/hossein/DataSection/DeepLearning/ImageNet_DataSet
TRAINING_DIR=training_set_t12/
VAL_DIR=imagenet_val/
SAVE_DIR=./snapshots/simpnet/

EPOCHS=100
BATCH_SIZE=128
WORKER=2

python imagenet_train.py $IMAGENET_DIR --train_dir_name $TRAINING_DIR --val_dir_name $VAL_DIR \
 --arch $MODEL_NAME --save_dir $SAVE_DIR -j $WORKER --epochs $EPOCHS --batch-size $BATCH_SIZE
```
executing it results in the following error : 
```
hossein@hossein:/media/hossein/tmpstore/tstPyTorch$ sh training_sequence.sh 
=> creating model 'resnet18'
... 

=> parameter : Namespace(arch='resnet18', batch_size=128, data='/media/hossein/DataSection/DeepLearning/ImageNet_DataSet', epochs=100, evaluate=False, lr=0.1, momentum=0.9, prefix='2018-05-02-652', print_freq=200, resume='', save_dir='./snapshots/simpnet/', start_epoch=0, train_dir_name='training_set_t12/', val_dir_name='imagenet_val/', weight_decay=0.0001, workers=2)
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:397: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
 [resnet18] ::   0/100 ----- [[2018-05-02 07:46:57]] [Need: 00:00:00]
Epoch: [0][0/10010]	Time 8.788 (8.788)	Data 7.033 (7.033)	Loss 7.0230 (7.0230)	Prec@1 0.000 (0.000)	Prec@5 0.000 (0.000)
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.c line=36 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "imagenet_train.py", line 304, in <module>
    main()
  File "imagenet_train.py", line 138, in main
    train(train_loader, model, criterion, optimizer, epoch, log)
  File "imagenet_train.py", line 184, in train
    losses.update(loss.data[0], input.size(0))
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:36
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:184
Aborted (core dumped)
```

Whats the issue here? 
Thank you very much in advance

**Comment by Coderx7** [comment]
Upon further investigations, I found out, the error is caused because one label is 1000! 
here is the error log : 
```
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:397: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
/home/hossein/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:156: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
 [resnet18] ::   0/100 ----- [[2018-05-03 16:40:03]] [Need: 00:00:00]
i:  0
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
target_var:  Variable containing:
 
[torch.cuda.LongTensor of size 128 (GPU 0)]

loss:  torch.Size([1])
Epoch: [0][0/10010]	Time 9.044 (9.044)	Data 7.229 (7.229)	Loss 7.0233 (7.0233)	Prec@1 0.000 (0.000)	Prec@5 0.000 (0.000)
i:  1
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  2
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  3
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  4
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  5
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  6
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
loss:  torch.Size([1])
i:  7
output:  torch.Size([128, 1000])
output(target_var):  torch.Size([128])
target_var:  Variable containing:
   32
  210
  546
  432
  932
  116
  229
  171
  484
  271
  594
  211
  207
  406
  401
  499
  332
  265
   58
  253
  662
  381
  152
  277
  677
   64
  235
  804
  981
  296
  862
  358
  868
  760
  161
  139
  461
  893
  473
  215
  736
    8
  387
  614
  988
  129
  765
  652
   11
  492
  301
  931
  809
  300
  889
  411
  780
  468
  718
  956
  790
  877
  546
   74
  123
   14
  422
  262
  163
   28
  514
  585
  683
  210
  551
   97
   15
  719
  816
  680
  237
  285
  291
  378
   13
  762
  743
  397
  677
  404
  637
  443
  625
  453
   40
  630
   26
  109
  695
  664
   60
  128
  904
  753
  969
   50
  158
  265
  687
  240
  191
  429
  267
  654
  501
  574
  669
  958
  295
  282
  417
  425
  544
   84
 1000
  901
  768
  547
[torch.cuda.LongTensor of size 128 (GPU 0)]

/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:101: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu line=113 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "imagenet_train.py", line 314, in <module>
    main()
  File "imagenet_train.py", line 140, in main
    train(train_loader, model, criterion, optimizer, epoch, log)
  File "imagenet_train.py", line 185, in train
    loss = criterion(output, target_var)
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 679, in forward
    self.ignore_index, self.reduce)
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1161, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, size_average, ignore_index, reduce)
  File "/home/hossein/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1052, in nll_loss
    return torch._C._nn.nll_loss(input, target, weight, size_average, ignore_index, reduce)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THCUNN/generic/ClassNLLCriterion.cu:113
terminate called after throwing an instance of 'std::runtime_error'
  what():  cuda runtime error (59) : device-side assert triggered at /pytorch/torch/lib/THC/generic/THCStorage.c:184
Aborted (core dumped)

```

**Comment by Coderx7** [comment]
Thanks to dear God, I finally found it.
There was an empty folder inside my training folder, removed it and everything is fine :)
